# Generated by Django 2.0.1 on 2018-01-29 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userName', models.CharField(max_length=150)),
                ('userPhoneNumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('callStatus', models.CharField(blank=True, choices=[('r', 'requested'), ('c', 'completed'), ('f', 'failed')], default='r', help_text='Call Status', max_length=1)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.DeleteModel(
            name='Call',
        ),
    ]
