# Generated by Django 2.0.1 on 2018-02-01 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_auto_20180129_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='callrequest',
            old_name='callStatus',
            new_name='call_status',
        ),
        migrations.RenameField(
            model_name='callrequest',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='callrequest',
            old_name='userName',
            new_name='your_name',
        ),
        migrations.RemoveField(
            model_name='callrequest',
            name='userPhoneNumber',
        ),
        migrations.AddField(
            model_name='callrequest',
            name='your_phone_number',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
